### ISSUE TITLE
Various failures on linux + python3

### ISSUE THREAD

**Issue by anntzer** [conda/menuinst#19]
In `linux.py`:
- the `utils` and `freedesktop` imports should be relative (`from .utils import ...`)
- there is no `get_executable` defined anywhere so the import fails.
- `tree.write` (line 88) tries to write bytes to a unicode-opened file.
- the 3rd argument to `ShortCut.__init__` should be `target_prefix`, not `prefix` (also line 203).
  Even after fixing all this, running `menuinst.install` wiped out my KDE menu instead of installing a proper menu entry :-(

**Comment by msarahan** [comment]
Thanks for your report.  It sounds like you are actually trying to use this on Linux.  That's more than we can currently say.  We use menuinst only on Windows right now - the rest of the code is legacy.  We welcome any PRs you might put together, but we are not otherwise planning on fixing these issues right now.

**Comment by anntzer** [comment]
Please remove/disable/put a big warning on the Linux code then, that'll avoid having someone else destroy their KDE menu and having to spend time figuring out how to restore it :-(

**Comment by msarahan** [comment]
Fair enough.  I'll add warnings to the README and discuss removing code internally.

**Comment by ccordoba12** [comment]
@msarahan, can we try to make it work on Linux before removing it?

**Comment by msarahan** [comment]
Sure - by all means, if you have time and want to fix it, then I'll be happy to review any changes.  I don't have time to fix this myself.
