### ISSUE TITLE
Update on PyPI required

### ISSUE THREAD

**Issue by pylang** [conda/menuinst#65]
When trying to `> pip install menuinst` in a Python 3.6, I get this response:

```bash
pip install menuinst
Collecting menuinst
  Could not find a version that satisfies the requirement menuinst (from versions: )
No matching distribution found for menuinst
You are using pip version 9.0.1, however version 9.0.3 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
```

Running `> pip show menuinst` shows the latest release is 1.0.0:

```bash
pip search menuinst
menuinst (1.0.0)  - cross platform install of menu items
  INSTALLED: 1.4.7
  LATEST:    1.0.0
You are using pip version 9.0.1, however version 9.0.3 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
```

This is verified when [searching `menuinst` at PyPI](https://pypi.python.org/pypi/menuinst).

At the moment, this hinders installing `menuinst` via pip.  Can the latest releases be published to PyPI?

**Comment by mingwandroid** [comment]
Why not conda install it? It is a package maintained by Anaconda Inc after
all.

**Comment by pylang** [comment]
I'm running test environments with tox, which use pip to install dependencies (such as `menuinst`).  I'm not aware of any means of installing and invoking conda packages in an environment setup by tox.

**Comment by sal-git** [comment]
I'm also having this problem.

@mingwandroid I cannot use conda to install it because I get 

```
C:\Users\Slightcap\Desktop\PDF_PARSE>conda install -c anaconda menuinst
Traceback (most recent call last):
  File "C:\Python34\Scripts\conda-script.py", line 6, in <module>
    from pkg_resources import load_entry_point
  File "c:\python34\lib\site-packages\pkg_resources\__init__.py", line 3095, in <module>
    @_call_aside
  File "c:\python34\lib\site-packages\pkg_resources\__init__.py", line 3079, in _call_aside
    f(*args, **kwargs)
  File "c:\python34\lib\site-packages\pkg_resources\__init__.py", line 3108, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "c:\python34\lib\site-packages\pkg_resources\__init__.py", line 570, in _build_master
    ws.require(__requires__)
  File "c:\python34\lib\site-packages\pkg_resources\__init__.py", line 888, in require
    needed = self.resolve(parse_requirements(requirements))
  File "c:\python34\lib\site-packages\pkg_resources\__init__.py", line 774, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'menuinst' distribution was not found and is required by conda
```

**Comment by pylang** [comment]
I have decided to deprecate my use of `menuinst`, but I am curious to understand the workflow restrictions that have impeded pushing an update to pip.   Is it solely a maintenance issue or are there other factors involved?  I notice [this package was originally maintained by Enthought][0].  Does  Continuum/Anaconda not maintain it any longer?  Many thanks.

  [0]: https://pypi.org/project/menuinst/

**Comment by msarahan** [comment]
It is primarily because we maintain this tool really only for our own use.  We produce conda packages, and that's all that we need.  We have no incentive to maintain a PyPI package, and no community member has stepped up to contribute that extra bit.

Just a matter of insufficient resources and prioritization.

**Comment by antoniovazquezblanco** [comment]
Sorry to bring up such an old thread.

I have an existing python installation and want to install conda. This is a dependency for the conda package and I am unable to install conda via pip which is my preferred way given that it will not bloat my system with second python installations.

As far as I know, this package uses setuptools thus suporting the `python setup.py sdist` to publish source distributions and the only extra step it takes to publish to PyPI is to have an account and use the command `twine upload dist/*` or upload by hand.

You even use AppVeyor wich supports artifacts and that command could be used to generate the required files to upload to PyPI whenever a new release takes place.

**Comment by msarahan** [comment]
Conda doesn't work well in the context of a system python.  It manages python as one of its own dependencies.  It can't currently introspect your system to satisfy that, and it definitely shouldn't alter your system.  You may be interested in the standalone conda executables, which can create and manipulate environments, but which lack the environment activation code: https://repo.anaconda.com/pkgs/misc/conda-execs/

To understand this better, you should check out https://discuss.python.org/t/drawing-a-line-to-the-scope-of-python-packaging/883 - there's a lot of annoying complexity to consider.  It's not at all a matter of "if you just uploaded an sdist, I could use conda."  You might make it work, but its binary dependencies (the SAT solver) may not be easy to obtain, and then even if you get it to work, the question of conda modifying your system installation should scare you away from trying it.

From Anaconda's point of view, menuinst exists to serve conda's needs.  Those needs do not include providing a package on PyPI.  If a community member would like to volunteer to help us maintain that PyPI entry, we'd happily consider it, but we will not dedicate our efforts to this otherwise.

**Comment by antoniovazquezblanco** [comment]
Thanks for the insight. I will have a look at that!

**Comment by ktprezes** [comment]
Hello
I've tried to install menuinst in python3.8 for windows environment via `pip install menuinst` and received similiar errors too... :(

In my case these steps led to success:
- download zip-file of master branch of this repository
- unpack it somewhere in my system
- cd to the folder with unpacked files
- run command: `python setup.py install`
- celebrate the success and install conda right after that ;)
